spring.application.name=Contact Manager

spring.datasource.url = jdbc:postgresql://localhost:5432/contact
spring.datasource.username = contact
spring.datasource.password = contact
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true